spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/auth/realms/oauth-demo
          jwk-set-uri: http://localhost:9000/auth/realms/oauth-demo/protocol/openid-connect/certs
